# Generated by Django 3.0.7 on 2021-05-10 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=8)),
                ('conformpassword', models.CharField(max_length=8)),
                ('email', models.EmailField(max_length=254)),
                ('accountnumber', models.IntegerField(max_length=11)),
                ('amount', models.IntegerField()),
            ],
        ),
    ]
