# Generated by Django 3.0.7 on 2021-05-12 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Loginapp', '0002_auto_20210512_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bills',
            name='Invoiceamount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='bills',
            name='Invoiceno',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='bills',
            name='Vendorname',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='bills',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='bills',
            name='grnamount',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='bills',
            name='paymentmode',
            field=models.CharField(max_length=200),
        ),
    ]
